//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class course
    {
        public int id { get; set; }
        [DisplayName("Course Code")]
        public string course_id { get; set; }
        [DisplayName("Teacher ID")]
        public string teacher_id { get; set; }
        [DisplayName("Student Number")]
        public string student_d { get; set; }
        public string CheckDetailsMessage { get; set; }
    }
}
